# YAML DOCUMENT TO GENERATE AN APT GROUP WITH PARAMETERS
---
  Model: 2 #1 o 2
  Timer: 4 #minutes
  Level: 1 #1, 2 o 3
  Parameters: yes #YES o NO
  APTGroup: yes #YES o NO
  APTGroupName: AAA #Name of APT group
  PlatformName: linux #windows, linux
  Objective: yes #YES o NO
  ObjectivePhase: 13 #1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14

# Model: the user can select between the models: 1 or 2. Depending on this, a sequential real or random model will generate.
# Timer: time in minutes of total operation time.
# Level: Sets the degree of dificulty in a sequential random model
# Parameter: the user has the posibility to choose of the whant ton configure parámeters of the model. The options are yes or no
# APTGroup: ONLY IF USER SES YES TO PARAMETERS. Option to configure the name on the APT group. 
# APTGroupName: If a real model has been selected (Model: 1 or 2), a real APT group name must be assigned. Available names:  ['Alice 2.0', 'Check', 'Collection', 'Discovery', 'Enumerator', 'Printer Queue', 'Ransack', 'Service Creation Lateral Movement', 'Signed Binary Proxy Execution', 'Stowaway', 'Super Spy', 'Thief', 'Undercover', 'Windows Worm #1', 'Windows Worm #2', 'Windows Worm #3', 'Worm', 'You Shall (Not) Bypass']
# PlatformName: Select the victim platform. This parameter can only take the following values: windows, macos, linux.
# Objective: Option for the user to define an objective phase in the operation.
# ObjectivePhase: ONLY IF USER SES YES TO PARAMETERS. Option to select the objective Cyber Kill Chain phase.